version: '3'
services:
  rccar_driver:
    privileged: true
    network_mode: "host"
    devices: 
      - /dev/input/js0:/dev/input/js0
    image: "rxdu:rccar-ros2"
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"
    entrypoint: /bin/bash
    command: ["-c", "source /ros2_ws/install/setup.bash && ros2 launch f1tenth_stack bringup_driver.py"]
    restart: unless-stopped
