version: '3'
services:
  vesc_driver:
    privileged: true
    # ipc: "shareable"
    network_mode: "host"
    environment:
      - "ROS_DOMAIN_ID=0"
    devices: 
      - /dev/input/js0:/dev/input/js0
      # - /dev/shm:/dev/shm
    image: "rxdu:rccar-ros2"
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"
    command: ros2 launch f1tenth_stack bringup_vesc.py
    restart: unless-stopped

  rccar_teleop:
    privileged: true
    ipc: "shareable"
    environment:
      - "ROS_DOMAIN_ID=0"
    # network_mode: "host"
    # devices: 
    #   - /dev/shm:/dev/shm
    image: "rxdu:rccar-ros2"
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"
    command: ros2 launch f1tenth_stack bringup_teleop.py
    restart: unless-stopped
    depends_on:
      - "vesc_driver"
